### ISSUE TITLE
Thanks for making this!

### ISSUE THREAD

**Issue by edfilbasan** [rodrmig/myspace-music-player#1]
I've also been making a MySpace page for fun! This was really helpful.

**Comment by rodrmig** [comment]
Very happy to hear! I saw your github.io page, it looks great! Great work

**Comment by edfilbasan** [comment]
Thanks! Feel free to lift anything from my project for your own :)

It's all in react and unresponsive, but that was the beauty of the 2008 web.

**Comment by rodrmig** [comment]
Will do man. If you ever need a programmer for any project, I would love to be a part of it.
